name: Generate a build and push to another branch

on:
    push:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Push
        steps:
            - name: git-checkout
              uses: actions/checkout@v2

            -   uses: actions/setup-node@v2
                with:
                    node-version: '14'
            -   run: npm install
            -   run: npm run build

            - name: Push
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: dist
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
                  MESSAGE: "Build: ({sha}) {msg}"
